4 final
ratsu123/purple_dz pull request #5
Opened 2023-12-22 06:48 UTC by ratsu123

2023-12-24 19:55 UTC, Levitinn requested changes
есть небольшие комментарии

2023-12-24 19:55 UTC, Levitinn commented on 3-Finio/styles/components.css
> +	margin-bottom: 15px;
лишний отступ? если н должен быть, но явно не у этой кнопки, а возможно паддингом секции или блока

2023-12-24 19:55 UTC, Levitinn commented on 3-Finio/styles/components.css
> +	padding-left: 2rem;
кажется паддинг здесь лишний. ты же выравниваешь через флекс, почему не сделать с его помощью отступ?

2023-12-24 19:55 UTC, Levitinn commented on 3-Finio/styles/components.css
> +.security__icon {
посмотри внимательно, img вылазит за див в котором лежит у второго и 3 пункта

2023-12-24 19:55 UTC, Levitinn commented on 3-Finio/index.html
![image](https://github.com/ratsu123/purple_dz/assets/44999446/32712325-49e8-4e15-8d3d-c1221f1fd07b)
 они точно не должны быть по центру в мобильной версии?

2023-12-25 09:01 UTC, ratsu123 commented on 3-Finio/index.html
У меня тоже был такой же вопрос, но в макете они слева

2023-12-25 09:09 UTC, merged